/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cloth;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yolgezer
 */
public class NewTransporation extends javax.swing.JFrame {
     DatabaseProcess dp = new DatabaseProcess();
             private Connection con = null;
             private Statement statement = null;
             private PreparedStatement preparedStatement =null;
             DefaultTableModel clothT;
             DefaultTableModel clothTakerT;
             DefaultTableModel transporterT;
             
             int clothId=-1;
             int transporterId=-1;
             int personId=-1;
             int hangarId=-1;

    /**
     * Creates new form yeniRota
     */
             
    public NewTransporation() {
        initComponents();
        this.setLocationRelativeTo(null);
        //jLabelDelivered.setText(" ");
        //onwaylabel.setText(" ");
        //avaliablelabel.setText(" ");
         clothT = (DefaultTableModel) clothTable.getModel();
         clothTakerT = (DefaultTableModel)clothTakerTable.getModel();
          transporterT = (DefaultTableModel) transporterTable.getModel();
       
       showClothes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        clothTakerTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transporterTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ButtonCreateTransportation = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        clothTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        clothTakerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Ali", "Kadri", "M", "M", null, null},
                {null, "Batuhan", "Bayrak", "L", "XL", null, null}
            },
            new String [] {
                "ID", "Name", "Surname", "Upper Size", "Lower Size", "City", "District"
            }
        ));
        clothTakerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clothTakerTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(clothTakerTable);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Cloth");

        transporterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2", "Ali", "Kardemir"},
                {"3", "Mehmet", "Ay"}
            },
            new String [] {
                "Transporter Id", "Name", "Surname"
            }
        ));
        transporterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transporterTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(transporterTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("ClothTaker");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Transporter");

        jPanel4.setBackground(new java.awt.Color(204, 153, 0));

        jLabel3.setBackground(new java.awt.Color(204, 153, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Create a new Transportation");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(313, 313, 313))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ButtonCreateTransportation.setBackground(new java.awt.Color(51, 51, 51));
        ButtonCreateTransportation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonCreateTransportation.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCreateTransportation.setText("Create Transportation");
        ButtonCreateTransportation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreateTransportationActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        clothTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"6", "T-Shirt", "M"},
                {"11", "Pants", "XL"}
            },
            new String [] {
                "Cloth Id", "Cloth Type", "Cloth Size"
            }
        ));
        clothTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clothTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(clothTable);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newTransportation.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(210, 210, 210)
                .addComponent(jLabel6)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonCreateTransportation)
                        .addGap(287, 287, 287)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(141, 141, 141))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(ButtonCreateTransportation))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Hangar at= new Hangar();
        at.setVisible(true);
        at.pack();
        at.setLocationRelativeTo(null);
        at.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clothTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clothTableMouseClicked
        int selectedRow= clothTable.getSelectedRow();
        String temp;
        temp=clothTable.getValueAt(selectedRow, 0).toString();
        clothId=Integer.parseInt(temp);
       
    }//GEN-LAST:event_clothTableMouseClicked

    private void clothTakerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clothTakerTableMouseClicked
        int selectedRow= clothTakerTable.getSelectedRow();
        String temp;
        personId=Integer.valueOf((String)clothTakerTable.getValueAt(selectedRow, 0).toString());
    }//GEN-LAST:event_clothTakerTableMouseClicked

    private void transporterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transporterTableMouseClicked
        int selectedRow= transporterTable.getSelectedRow();
        transporterId=Integer.valueOf((String)transporterTable.getValueAt(selectedRow, 0).toString());
        
    }//GEN-LAST:event_transporterTableMouseClicked

    private void ButtonCreateTransportationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateTransportationActionPerformed
        hangarId=dp.getHangarId(LoginPage.hangarName);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
        LocalDateTime now = LocalDateTime.now();
        
        dp.insertTakes(clothId, personId,
                transporterId, hangarId, dtf.format(now));
        Hangar at= new Hangar();
        at.setVisible(true);
        at.pack();
        at.setLocationRelativeTo(null);
        at.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); // TODO add your handling code here:
        
    }//GEN-LAST:event_ButtonCreateTransportationActionPerformed

    
    public void showClothes(){
        clothT.setRowCount(0);
        clothTakerT.setRowCount(0);
        transporterT.setRowCount(0);
        
        ArrayList<ClothTable> cloths = new ArrayList<ClothTable>();
        ArrayList<ClothTaker> clothTakers = new ArrayList<ClothTaker>();
        ArrayList<Transporter> transporters = new ArrayList<Transporter>();
        
        cloths = dp.hangarCloth(LoginPage.hangarName);
        clothTakers= dp.hangarClothTaker();
        transporters= dp.hangarTransporter(LoginPage.hangarName);
                
                   if(cloths !=null){// if the workers not null we are gonna add all the user in to object array, why we are doing that because jTAble takes only object variables. For that reason, we 
                for(ClothTable urr : cloths){
                    if(urr.getClothId()!=-1 && urr.getClothType()!= null && urr.getClothSize()!=null ){
                        Object[] object = {urr.getClothId(),urr.getClothType(),urr.getClothSize()};
                        clothT.addRow(object);//adding rows into table 
                    }
                    
                }
            
           }
                   if(cloths.size()==0){
                       //onwaylabel.setText("No Entry");
                   }
              
                
                 if(clothTakers !=null){// if the workers not null we are gonna add all the user in to object array, why we are doing that because jTAble takes only object variables. For that reason, we 
                for(ClothTaker urr : clothTakers){
                    if(urr.getName()!=null && urr.getSurname()!= null && urr.getUpperSize()!=null && urr.getLowerSize()!=null && urr.getCity()!=null && urr.getDistrict()!=null ){
                        Object[] object = {urr.getId(),urr.getName(),urr.getSurname(),urr.getUpperSize(),urr.getLowerSize(),urr.getCity(),urr.getDistrict()};
                        clothTakerT.addRow(object);//adding rows into table 
                    }
                    
                }
            
           }
                 if(clothTakers.size()==0){
                     //jLabelDelivered.setText("No Entry");
                 }
                 
                  if(transporters !=null){// if the workers not null we are gonna add all the user in to object array, why we are doing that because jTAble takes only object variables. For that reason, we 
                for(Transporter urr : transporters){
                    if(urr.getTransporterId()!=-1 && urr.getName()!= null && urr.getSurname()!=null ){
                        Object[] object = {urr.getTransporterId(),urr.getName(),urr.getSurname()};
                        transporterT.addRow(object);//adding rows into table 
                    }
                    
                }
            
           }
                  if(transporters.size()==0){
                      // avaliablelabel.setText("No Entry");
                  } 
     }  
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTransporation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTransporation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTransporation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTransporation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTransporation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCreateTransportation;
    private javax.swing.JTable clothTable;
    private javax.swing.JTable clothTakerTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable transporterTable;
    // End of variables declaration//GEN-END:variables
}
